// <auto-generated />
namespace EmployeeBook.WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CvDocuments1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CvDocuments1));
        
        string IMigrationMetadata.Id
        {
            get { return "201506181438345_CvDocuments1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
